title: "El Hadji Ousseynou ACCRACHI"
description: "Portfolio académique — Enseignant-Chercheur en Mathématiques, Statistique et Sciences des données"
theme: jekyll-theme-modernist
markdown: kramdown

# Photo de profil
profile_image: "img/EOA.jpg"
