title: "El Hadji Ousseynou ACCRACHI"
logo: img/EOA.jpg
description: "Statisticien - Mathématicien - Analyste de données"
show_downloads: true
theme: jekyll-theme-modernist
lang: fr
markdown: Kramdown
